name: Build static lib

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    container: gohornet/goreleaser-cgo-cross-compiler:1.16.3
    steps:

    - name: checkout-repo
      uses: actions/checkout@v2

    - name: parse-version
      id: parse-version
      run: echo "::set-output name=ROCKSDB_VERSION::`cat build.sh | grep rocksdb_version= | sed 's/rocksdb_version=\"\(.*\)\"/\1/'`"

    - name: build-libs
      run: make libs

    - name: commit-changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add dist
        git commit -m "Build static libs for RocksDB v${{ steps.parse-version.outputs.ROCKSDB_VERSION }}"
        git checkout -b "release/hornet-rocksdb-${{ steps.parse-version.outputs.ROCKSDB_VERSION }}"
        git push --set-upstream origin "release/hornet-rocksdb-${{ steps.parse-version.outputs.ROCKSDB_VERSION }}"